    - name: Clone and patch GRUB
      run: |
        git clone https://git.savannah.gnu.org/git/grub.git
        cd grub
        
        # Сначала запускаем bootstrap чтобы создать файлы
        ./bootstrap
        
        # Копируем setup_var.c в нужную папку
        cp ../setup_var.c ./grub-core/commands/
        
        # Применяем патч к Makefile.core.def
        patch -p1 < ../Makefile.core.def.patch
        
    - name: Build GRUB
      run: |
        cd grub
        ./configure --target=x86_64 --with-platform=efi
        make
