- name: Clone and patch GRUB
  run: |
    git clone https://git.savannah.gnu.org/git/grub.git
    cd grub
    ./bootstrap
    cp ../setup_var.c ./grub-core/commands/
    patch -p1 < ../Makefile.core.def.patch
- name: Build GRUB
  run: |
    cd grub
    ./configure --target=x86_64 --with-platform=efi
    make
