name: Build GRUB with setup_var

on: 
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        repository: datasone/grub-mod-setup_var
        
    - name: Build GRUB
      run: |
        chmod +x build-grub.sh
        ./build-grub.sh
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: grub-efi
        path: grub-bin/
